### ISSUE TITLE
Expressions not allowed at the top level

### ISSUE THREAD

**Issue by ronnits10** [Erotemic/xdoctest#116]
I have an error in my code. I am very new to swift and started coding. The error in my code is saying Expressions are not allowed at the top level can you please help me with this problem. Thank you.

Here's my code
________________________________________________________________________________________________________________
import UIKit

var str = "Hello Playground"
print(str) -- error here

**Comment by ronnits10** [comment]
PLEASE HELP ME!

**Comment by Erotemic** [comment]
I'm not sure how to respond to this. This is for the xdoctest Python module. Not sure if you are in the right place. If this is for xdoctest please describe: 

* The issue
* The expected results
* How to reproduce it 
* Steps tried so far

**Comment by Erotemic** [comment]
No follow up. Closing. If this is still an issue, add more details and reopen.
