### ISSUE TITLE
Incompatibility with pytest-matrix

### ISSUE THREAD

**Issue by jayvdb** [Erotemic/xdoctest#81]
see https://github.com/dburton90/pytest_matrix/issues/2

**Comment by Erotemic** [comment]
Thanks for the report. 

Do you have a MWE? Does this happen if pytest-matrix is simply installed? Or do you have to use it somehow for this error to occur?

**Comment by jayvdb** [comment]
I had just installed it, not trying to use it at all.

That section of code looks like it is trying to determine whether it should activate.

**Comment by Erotemic** [comment]
I was able to reproduce and fix this issue in #82 and that will be released when version 0.14.0 is released, which I plan do to in the next few days.

**Comment by Erotemic** [comment]
#82 has been merged and 0.14.0 has been released on pypi, so this should be fixed now.
